### ISSUE TITLE
Downloaded videos are invalid data.

### ISSUE THREAD

**Issue by thepuar** [dimme/tapo-cli#1]
Hii, everything was working properly until last days. I can download videos but can't open. I think TAPO changed format or something.
Someone have the same problem?
![image](https://github.com/dimme/tapo-cli/assets/36414724/0aa6c2f8-5b8b-4e06-a277-1ea03b1ab272)

**Comment by igoriok** [comment]
They added encryption:
`'encryptionMethod': 'AES-128-CTR', 'decryptionInfo': {'key': '<BASE64>', 'iv': '<BASE64>'}`

**Comment by dimme** [comment]
I will take a closer look at it when I have some time. In the meantime, you are welcome to do a pull request if you have a solution.

**Comment by thepuar** [comment]
Sadly I have no idea about python, but I can create a Java version(when I have time) and reference your proyect as creator if you are agree.
;)

**Comment by dimme** [comment]
Do as you wish =)

**Comment by igoriok** [comment]
Made in Go: https://github.com/igoriok/tapo-cli

`download-old` - is using old endpoint and encryption (if needed)
Usage: `download-old --token <TOKEN> --device <DEVICE-ID> --since 1 --days 1`

`download` - is using new endpoint and ffmpeg (required)
Usage: `download --token <TOKEN> --device <DEVICE-ID> --since 1 --days 1`

I'll add authentication when I have more time.

**Comment by dimme** [comment]
This has been fixed now. Thanks for the heads up.
